spring:
  application:
    name: demo
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR